#!/usr/bin/env bash
### home row control: use big keys on the home row as ctrl modifiers

## Author: Ryan Prior <ryanprior@gmail.com>

## This file is free software dedicated to the public domain. See
## COPYING or https://creativecommons.org/publicdomain/zero/1.0/ for
## details.

function enter_acts_as_ctrl ()
{
    xmodmap -e "remove mod4 = Hyper_L"
    xmodmap -e "keycode 36 = Hyper_L"
    xmodmap -e "add Control = Hyper_L"
    xmodmap -e "keycode any = Return"
}

function caps_acts_as_ctrl ()
{
    xmodmap -e "remove lock = Caps_Lock"
    xmodmap -e "keycode 66 = XF86Finance"
    xmodmap -e "add Control = XF86Finance"
    xmodmap -e "keycode any = Caps_Lock"
}

(
    enter_acts_as_ctrl
    caps_acts_as_ctrl
    xcape -e "Hyper_L=Return;XF86Finance=Caps_Lock"
) 2>&1 >/dev/null &
