#!/bin/sh
### home row control: use big keys on the home row as ctrl modifiers

## Author: Ryan Prior <ryanprior@gmail.com>

## This file is free software dedicated to the public domain. See
## COPYING or https://creativecommons.org/publicdomain/zero/1.0/ for
## details.

xmodmap maps/enter.map
xmodmap maps/caps.map
exec xcape -e "Hyper_L=Return;Control_R=Caps_Lock"
